# This is a basic workflow to help you get started with Actions

name: CI
on:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Print GitHub Context
        run: |
          echo "GITHUB CONTEXT:"
          echo '${{ toJSON(github) }}'
      - name: Show content
        run: |
          cat README.md
      - run: exit 1
      - name: The job has failed
        if: ${{ failure() }}          
      
