name: docker
on:
  push:
    branches: [ main ]
jobs:
  non-docker:
    runs-on: ubuntu-latest
    steps:
      - name: simple
        run: pwd
      - name: variable
        run: echo "$GITHUB_WORKSPACE"
      - name: list
        run: ls
  container-test-job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    container:
      image: ghcr.io/diffeny/busybox:latest
      credentials:
         username: ${{ github.actor }}
         password: ${{ secrets.github_token }}      
      env:
        NODE_ENV: development
      options: --cpus 1
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
      - uses: actions/checkout@v4
      - name: update
        run: apt update -y
      - name: inside
        run: apt install -y tree
      - name: check folders
        run: echo "${{github.workspace}}"
      - name: pwd
        run: pwd && ls
